#!/bin/sh

offset="+09:00"
orientation="-Orientation=Horizontal"

__usage() {
	echo "Usage: ${0##*/} [-lrz:] jpeg [jpeg ...]" >&2
	exit 1
}

while getopts 'lrz:' cmd_arg; do
	case "${cmd_arg}" in
	l)	orientation="-Orientation=Rotate 270 CW" ;;
	r)	orientation="-Orientation=Rotate 90 CW" ;;
	z)	offset="$OPTARG" ;;
	*)	__usage ;;
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	__usage
fi

exiftool -quiet -preserve -overwrite_original \
	-DateTimeOriginal'<'FileModifyDate' \
	-OffsetTimeOriginal="${offset}" \
	-Make=3COINS \
	-Model='MINI TOY CAMERA 2513/KRTC' \
	"${orientation}" \
	"$@"
