#!/bin/sh
#
#  exif4toycamera - Adding Exif meta-data for 3COINS MINI TOY CAMERA
#
#  Copyright (c) 2025 Masato Minda
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.
#
#  $Id: exif4toycamera,v 1.4 2025/12/09 03:44:44 minmin Exp $

offset="+09:00"
orientation="Horizontal"

__usage() {
	echo "Usage: ${0##*/} [-lr] [-z TZoffset] file [file ...]" >&2
	exit 1
}

while getopts 'lrz:' cmd_arg; do
	case "${cmd_arg}" in
	l)	orientation="Rotate 270 CW" ;;
	r)	orientation="Rotate 90 CW" ;;
	z)	offset="$OPTARG" ;;
	*)	__usage ;;
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	__usage
fi

exiftool -quiet -preserve -overwrite_original \
	-AllDates'<FileModifyDate' \
	-OffsetTime="${offset}" \
	-OffsetTimeOriginal="${offset}" \
	-OffsetTimeDigitized="${offset}" \
	-Make=3COINS \
	-Model='MINI TOY CAMERA 2513/KRTC' \
	-FocalLength='2.2mm' \
	-FNumber='2.8' \
	-Orientation="${orientation}" \
	"$@"
